ui:
	./../node_modules/@vue/cli/bin/vue.js ui

serve:
	./node_modules/@vue/cli-service/bin/vue-cli-service.js serve

up:
	docker-compose -f ../nginx/docker-compose.yml up -d

down:
	docker-compose -f ../nginx/docker-compose.yml down

ps:
	docker-compose -f ../nginx/docker-compose.yml ps

logs:
	docker-compose -f ../nginx/docker-compose.yml logs
