language: node_js
node_js:
  - "10"
env:
  - TRAVIS_BUILD_DIR=./client/
dist: trusty
sudo: false
before_install:
  - yarn install
  - yarn add @vue/cli
cache: yarn
script:
  - vue build
notifications:
  email:
    on_success: never
