version: '3'
services:
  nginx:
    container_name: 'nginx'
    image: nginx:1.14
    ports:
      - 8000:80
    volumes:
      - ../client/dist:/usr/share/nginx/html:ro
    network_mode: 'chatroom'
    restart: always
